Add Dependabot to keep project updated
foundriesio/fioctl pull request #274
Opened 2023-09-23 16:24 UTC by camilamacedo86

## Description

Introduce Dependabot to ensure consistent and effortless updating of the project's dependencies.

GitHub's Dependabot will perform weekly checks and automatically create pull requests to update the Dockerfile, GitHub Actions, and go.mod dependencies. With a reliable Continuous Integration (CI) in place to validate the tool's functionality, this approach significantly streamlines the review process. This allows us to effortlessly keep our project updated, minimizing technical debt and promptly addressing any potential Common Vulnerabilities and Exposures (CVEs).

2023-09-25 12:47 UTC, vkhoroz commented
Although we don't have a `a reliable Continuous Integration (CI) in place` for this project, adding dependabot might give us some added value.

@doanac I think we can try this, unless you had bad experience with dependabot for Fioctl.

2023-09-25 16:37 UTC, camilamacedo86 commented
Hi @vkhoroz,

> Although we don't have a a reliable Continuous Integration (CI) in place for this project, adding dependabot might give us some added value.

That would be the goal of https://github.com/foundriesio/fioctl/pull/275

If we can ensure that the build is successful and the binary is functional, then I believe we can have confidence in updating the Go dependencies. The only scenario in which something might stop working would be if a new bug or regression is introduced in the updated dependency version. However, this seems highly unlikely to me, and consequently, I consider this to be a low-risk situation.

2023-09-26 12:21 UTC, vkhoroz requested changes
LGTM

Please, strip those comments, squash all your commits **locally**, force-push a single commit signed by your GPG (your can use `git commit -sS --amend` at the head for that), and force-push the updated commit history into your branch.

I will do the final sanity check for our SDLC rules, approve and merge this (using the rebase strategy).

No worries, you did a great job.
I wrote this whole paragraph jusy to let you better know in details our usual workflow.

2023-09-26 12:21 UTC, vkhoroz commented on .github/dependabot.yml
> +# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
Please, drop this comment.
We use dependabot in many projects already, so it is not something new to us.

2023-09-26 12:21 UTC, vkhoroz commented on .github/dependabot.yml
> +  # Maintain dependencies for go
Please, strip all these comments. The code is self-descriptive enough.

2023-09-27 10:05 UTC, camilamacedo86 commented
@vkhoroz all suggestions applied !

2023-09-28 13:50 UTC, vkhoroz approved these changes
LGTM

2023-09-28 13:51 UTC, merged